let words_9 = [ 'CASEXFILE', 'CLUEXHUNT', 'CRIMEXXRA', 'STAKEXXOU', 'DETECTXIV', 'WITNESSXE', 'MURDERSXX', 'SUSPECTXE', 'FORENSICS', 
        'EVIDENCEX', 'CRIMESCEN', 'MOTIVEXLO', 'SLEUTHING', 'PISTOLXED', 'CLUEXXXMA', 'TRAILXXLO', 'TRACKERXX', 'SHADOWING', 'PLOTXLINE', 
        'LEADXXXXX', 'HOOKXXXED', 'PROOFXRAY', 'DEDUCEXXX', 'RIDDLESXS', 'MYSTERYXE', 'FOLLOWXED', 'CHASEXXXX', 'BREAKXLOG', 'CIPHERXXX', 
        'SEARCHXED', 'SNOOPXXED', 'WARRANTXX', 'TRAILXXER', 'AGENTXXXX', 'CLUEXMAPX', 'PROFILEXX', 'CRACKXXED', 'SCANNERXS', 'LOGBOOKXX', 
        'SECRETSXS', 'CODEXLOGX', 'WITNESSXS', 'HUNTXXXED', 'CLOSEDXXX', 'HOLDINGSX', 'REPORTXXS', 'BULLETXXX', 'TRACEXXED','LOCKUPXXX', 
        'ARCHIVEXS']

let words_16 = [ 'MURDERXMYSTERYXX', 'CRIMEXSCENEXLOGX', 'CLUEXHUNTERXXXXX', 'CASEXFILEXLOGXXX', 'SECRETXAGENTXXXX', 'COLDXCASEXFILEXX', 
        'TRAILXLOGXMASTER', 'WITNESSXREPORTSX', 'SLEUTHXFILESXXXX', 'PISTOLXEVIDENCEX', 'STAKEOUTXMISSION', 'FORENSICXPROBEXX', 
        'SUSPECTXTRACKERX', 'MOTIVEXHUNTERXXX', 'CRIMEXDEDUCTIONX', 'EVIDENCEXLOCKEDX', 'TRACKINGXAGENTXX', 'CIPHERXMESSAGESX', 
        'DETECTIVEXNOTESX', 'WARRANTXSEARCHXX', 'PROFILEXMASTERXX', 'CLUEXSOLVINGXXXX', 'ARCHIVEXREPORTXX', 'RIDDLEXMASTERXXX', 
        'SECRETXMISSIONXX', 'BREAKINGXCLUEXXX', 'FOLLOWXTHEXLEADX', 'CODEDXMESSAGEXXX', 'CRIMINALXFILEXXX', 'MYSTERYXSOLVERXX', 
        'CASExTRACKINGXXX', 'EVIDENCEXPROOFXX', 'LOGBOOKXMASTERXX', 'HUNTXTHEXCLUEXXX', 'AGENTXOPERATESXX', 'SHADOWXTRACKERXX', 
        'REPORTXFINDINGXX', 'LOCKEDXMYSTERYXX', 'CRACKINGXCASExXX', 'WITNESSXSECRETXX', 'MISSIONXLOGXXXXX', 'TRAILXSLEUTHXXXX', 
        'HIDDENXEVIDENTXX', 'PROOFXHUNTINGXXX', 'CODEXBREAKINGXXX', 'SCANNERXREPORTXX', 'BULLETXPROOFXXXX', 'HOLDINGXPATTERNX', 
        'CLOSEDXCASExXXXX', 'CIPHERXHUNTINGXX'
        ]

let words_25 = [ 'MURDERXMYSTERYXFILEXLOGXX', 'CRIMEXSCENEXINVESTIGATION', 'CLUEXHUNTERXTRACKINGXCASE', 'SECRETXAGENTXMISSIONXFILE', 
        'COLDXCASEXFILEXDOCUMENTXX', 'TRAILXLOGXMASTERXREPORTXX', 'WITNESSXREPORTXEVIDENCEXX', 'SLEUTHXFILESXMYSTERYXLOGX', 
        'PISTOLXEVIDENCEXTRACKERXX', 'STAKEOUTXMISSIONXDETECTXX', 'FORENSICXPROBEXCASEXLOGXX', 'SUSPECTXTRACKERXREPORTXXX', 
        'MOTIVEXHUNTERXSECRETXLOGX', 'CRIMEXDEDUCTIONXFILEXLOGX', 'EVIDENCEXLOCKERXMYSTERYXX', 'TRACKINGXAGENTXCASEXFILEX', 
        'CIPHERXMESSAGEXDETECTIVEX', 'DETECTIVEXNOTESXMYSTERYXX', 'WARRANXSEARCHXCASEXLOGXXX', 'PROFILEXMASTERXTRACKINGXX', 
        'CLUESOLVINXMYSTERYXLOGXXX', 'ARCHIVEXREPORTXDETECTIVEX', 'RIDDLEMASTERXTRACKERXXXXX', 'SECRETXMISSIONXFILEXLOGXX', 
        'BREAKINGXCLUEXINVESTIGATE', 'FOLLOWXTHEXLEADXCASEXXXXX', 'CODEDXMESSAGEXMYSTERYXLOG', 'CRIMINALXFILEXTRACKINGXXX', 
        'MYSTERYXSOLVERXCASEXLOGXX', 'CASETRACKINXSECRETXLOGXXX', 'EVIDENCEXPROOFXDETECTIVEX', 'LOGBOOKXMASTERXMYSTERYXXX', 
        'HUNTXTHEXCLUEXFILEXLOGXXX', 'AGENTOPERATESXCASEXLOGXXX', 'SHADOWXTRACKERXMYSTERYXXX', 'REPORTFINDINGXDETECTIVEXX', 
        'LOCKEDXMYSTERYXCASEXLOGXX', 'CRACKINGXCASEXINVESTIGATE', 'WITNESSXSECRETXTRACKINGXX', 'MISSIONXLOGXDETECTIVEXLOG', 
        'TRAILSLEUTHXMYSTERYXLOGXX', 'HIDDENXEVIDENCEXCASEXLOGX', 'PROOFHUNTINGXMYSTERYXXXXX', 'CODEBREAKINGXCASEXLOGXXXX', 
        'SCANNERREPORTXDETECTIVEXX', 'BULLETPROOFXMYSTERYXLOGXX', 'HOLDINGPATTERNXCASEXLOGXX', 'CLOSEDXCASEXINVESTIGATION', 
        'CIPHERXHUNTINGXDETECTIVEX', 'INVESTIGATIONXMYSTERYXLOG']

let words_36 = [ 'MURDERXMYSTERYXFILEXLOGXDETECTIVEXXX', 'CRIMEXSCENEXINVESTIGATIONXMASTERXLOG', 'CLUEXHUNTERXTRACKINGXCASEXSECRETXXXX', 
        'SECRETXAGENTXMISSIONXFILEXEVIDENCEXX', 'COLDXCASEXFILEXDOCUMENTXTRACKINGXXXX', 'TRAILXLOGXMASTERXREPORTXDETECTIVEXXX', 
        'WITNESSXREPORTXEVIDENCEXHUNTERXCASEX', 'SLEUTHXFILESXMYSTERYXLOGXCIPHERXCASE', 'PISTOLXEVIDENCEXTRACKERXMISSIONXFILE', 
        'STAKEOUTXMISSIONXDETECTIVEXREPORTXXX', 'FORENSICXPROBEXCASEXLOGXSECRETXFILEX', 'SUSPECTXTRACKERXREPORTXMYSTERYXCASEX', 
        'MOTIVEXHUNTERXSECRETXLOGXEVIDENCEXXX', 'CRIMEXDEDUCTIONXFILEXLOGXTRACKINGXXX', 'EVIDENCEXLOCKERXMYSTERYXREPORTXDRXXX', 
        'TRACKINGXAGENTXCASEXFILEXHUNTERXLOGX', 'CIPHERXMESSAGEXDETECTIVEXMYSTERYXXX', 'DETECTIVEXNOTESXMYSTERYXLOGXREPORTXX', 
        'WARRANXSEARCHXCASEXLOGXEVIDENCEXFILE', 'PROFILEXMASTERXTRACKINGXDETECTIVEXXX', 'CLUESOLVINXMYSTERYXLOGXCIPHERXCASEXX', 
        'ARCHIVEXREPORTXDETECTIVEXMISSIONXLOG', 'RIDDLEMASTERXTRACKERXSECRETXFILEXXXX', 'SECRETXMISSIONXFILEXLOGXCLUEXHUNTERX', 
        'BREAKINGXCLUEXINVESTIGATIONXMYSTERYX', 'FOLLOWXTHEXLEADXCASEXDETECTIVEXLOGXX', 'CODEDXMESSAGEXMYSTERYXLOGXREPORTXXXX', 
        'CRIMINALXFILEXTRACKINGXSECRETXCASEXX', 'MYSTERYXSOLVERXCASEXLOGXEVIDENCEXXXX', 'CASETRACKINXSECRETXLOGXDETECTIVEXXXX', 
        'EVIDENCEXPROOFXDETECTIVEXMISSIONXXXX', 'LOGBOOKXMASTERXMYSTERYXREPORTXLOGXXX', 'HUNTXTHEXCLUEXFILEXLOGXTRACKINGXXXXX', 
        'AGENTOPERATESXCASEXLOGXSECRETXXXXXXX', 'SHADOWXTRACKERXMYSTERYXREPORTXXXXXXX', 'REPORTXFINDINGXDETECTIVEXLOGXXXXXXXX', 
        'LOCKEDXMYSTERYXCASEXLOGXHUNTERXXXXXX', 'CRACKINGXCASEXINVESTIGATIONXFILEXXXX', 'WITNESSXSECRETXTRACKINGXMYSTERYXXXXX', 
        'MISSIONXLOGXDETECTIVEXLOGXCASEXXXXXX', 'TRAILSLEUTHXMYSTERYXLOGXREPORTXXXXXX', 'HIDDENXEVIDENCEXCASEXLOGXFILEXXXXXXX', 
        'PROOFHUNTINGXMYSTERYXDETECTXXXXXXXXX', 'CODEXBREAKINGXCASEXLOGXREPORTXXXXXXX', 'SCANNERXREPORTXDETECTIVEXLOGXXXXXXXX', 
        'BULLETPROOFXMYSTERYXLOGXCASEXXXXXXXX', 'HOLDINGXPATTERNXCASEXLOGXFILEXXXXXXX', 'CLOSEDXCASEXINVESTIGATIONXLOGXXXXXXX', 
        'CIPHERXHUNTINGXDETECTIVEXLOGXXXXXXXX', 'INVESTIGATIONXMYSTERYXLOGXCASEXXXXXX']


