export const words_9 = [ 'CASEXFILE', 'CLUEXHUNT', 'CRIMESXXX', 'STAKEXOUT', 'DETECTIVE', 'WITNESSXX', 'MURDERSXX', 'SUSPECTXX', 'FORENSICS', 
        'EVIDENCEX', 'BLOODSPOT', 'MOTIVELOG', 'SLEUTHING', 'PISTOLXXX', 'CLUEXMAPX', 'TRAILXLOG', 'TRACKERXX', 'SHADOWING', 'PLOTXLINE', 
        'LEADXXXXX', 'HOOKEDXXX', 'PROOFXRAY', 'DEDUCEXXX', 'RIDDLESXX', 'MYSTERYXX', 'FOLLOWEDX', 'CHASEXXXX', 'BREAKXLOG', 'CIPHERXXX', 
        'SEARCHEDX', 'SNOOPINGX', 'WARRANTXX', 'TRAILERXX', 'AGENTSXXX', 'CLUEXMAPX', 'PROFILEXX', 'CRACKXXED', 'SCANNERXS', 'LOGBOOKXX', 
        'SECRETSXX', 'CODEXLOGX', 'WITNESSES', 'HUNTINGSX', 'CLOSEDXXX', 'HOLDINGSX', 'REPORTXXS', 'BLUEPRINT', 'TRACEDXXXd','LOCKUPXXX', 
        'ARCHIVEXS']

export const words_9_hints = [
        "A file related to a case in a crime investigation.",
        "A hunt for clues in a crime-solving game.",
        "A type of crime involving multiple elements.",
        "A phrase involving the act of staking something for an outcome.",
        "A person responsible for solving crimes, typically in a detective role.",
        "A person who observes and provides testimony in court.",
        "A crime involving death, often investigated by detectives.",
        "A person who is being investigated for a crime.",
        "Scientific methods used to solve crimes and identify criminals.",
        "A clue or object that supports the findings in an investigation.",
        "A stain or mark left by blood, often in crime scenes.",
        "A log that tracks the reasons behind a crime or investigation.",
        "The process of investigating and solving mysteries.",
        "A type of weapon often used in crime-related cases.",
        "A map or guide related to finding clues in a case.",
        "A log that tracks the journey of a trail left behind in an investigation.",
        "A device or tool used to follow or trace a person or object.",
        "The act of tracking someone in secret, often in criminal investigations.",
        "A diagram or list used to organize key events in an investigation.",
        "An important piece of information or clue in solving a case.",
        "A criminal or investigative term for tracking someone's actions.",
        "The act of confirming facts or verifying theories with evidence.",
        "A set of puzzles or challenges used in solving mysteries.",
        "A general term for something mysterious or unsolved.",
        "The act of following someone or something in an investigation.",
        "A sudden or intense pursuit of someone or something.",
        "A log of important breakthroughs in a case.",
        "A puzzle involving code-breaking for uncovering secrets.",
        "A search for clues or evidence related to a case.",
        "The act of spying or investigating someone secretly.",
        "A legal document granting permission to search for evidence.",
        "A trailer used in an investigation or surveillance operation.",
        "A group of professionals working together on cases.",
        "A map or guide to solving a mystery or finding a clue.",
        "A process of solving a case by cracking clues or secrets.",
        "A tool used in a detective’s investigation, often scanning for clues.",
        "A notebook containing critical information for solving crimes.",
        "A hidden or secret investigation report or case information.",
        "A secured location for storing evidence in an investigation.",
        "A detailed file containing crucial case details and findings.",
        "A piece of evidence proving the validity of a theory.",
        "A process of solving clues in an investigation to catch a criminal."
    ];

export const words_16 = [ 'MURDERXMYSTERYXX', 'CRIMEXSCENEXLOGX', 'CLUEXHUNTERXXXXX', 'CASEXFILEXLOGXXX', 'SECRETXAGENTXXXX', 'COLDXCASEXFILEXX', 
        'TRAILXLOGXMASTER', 'WITNESSXREPORTSX', 'SLEUTHXFILESXXXX', 'PISTOLXEVIDENCEX', 'STAKEOUTXMISSION', 'FORENSICXPROBEXX', 
        'SUSPECTXTRACKERX', 'MOTIVEXHUNTERXXX', 'CRIMEXDEDUCTIONX', 'EVIDENCEXLOCKEDX', 'TRACKINGXAGENTXX', 'CIPHERXMESSAGESX', 
        'DETECTIVEXNOTESX', 'WARRANTXSEARCHXX', 'PROFILEXMASTERXX', 'CLUEXSOLVINGXXXX', 'ARCHIVEXREPORTXX', 'RIDDLEXMASTERXXX', 
        'SECRETXMISSIONXX', 'BREAKINGXCLUEXXX', 'FOLLOWXTHEXLEADX', 'CODEDXMESSAGEXXX', 'CRIMINALXFILEXXX', 'MYSTERYXSOLVERXX', 
        'CASExTRACKINGXXX', 'EVIDENCEXPROOFXX', 'LOGBOOKXMASTERXX', 'HUNTXTHEXCLUEXXX', 'AGENTXOPERATESXX', 'SHADOWXTRACKERXX', 
        'REPORTXFINDINGXX', 'LOCKEDXMYSTERYXX', 'CRACKINGXCASExXX', 'WITNESSXSECRETXX', 'MISSIONXLOGXXXXX', 'TRAILXSLEUTHXXXX', 
        'HIDDENXEVIDENTXX', 'PROOFXHUNTINGXXX', 'CODEXBREAKINGXXX', 'SCANNERXREPORTXX', 'BULexport constXPROOFXXXX', 'HOLDINGXPATTERNX', 
        'CLOSEDXCASExXXXX', 'CIPHERXHUNTINGXX'
        ]

export const words_16_hints = [
        "A file detailing a murder mystery case investigation.",
        "A log documenting a crime scene investigation.",
        "The pursuit of clues in a hunt to solve a mystery.",
        "A file documenting the details of a case investigation.",
        "A secret mission file of an agent working undercover.",
        "A file related to an unsolved cold case awaiting investigation.",
        "A master report logging evidence in a case investigation.",
        "A report documenting witness testimonies and key evidence.",
        "A series of files containing information on solved mysteries.",
        "A case file documenting the discovery and analysis of evidence.",
        "A mission involving observation and gathering information.",
        "A forensic investigation of crime-related evidence and documents.",
        "A tracker used to monitor a suspect’s actions and movements.",
        "A hunt for a criminal based on evidence of their motivation.",
        "A process of analyzing evidence to make logical deductions.",
        "A locked file containing vital evidence for a mystery case.",
        "An agent's report tracking a criminal investigation’s details.",
        "A coded message that requires a detective's expertise to decode.",
        "A detective’s notes, crucial for solving a case.",
        "A document authorizing the search of a crime scene or suspect.",
        "A detailed profile of a master detective tracking a criminal.",
        "A process of solving clues and uncovering secrets in a case.",
        "A report documenting archived cases and critical findings.",
        "A tracker solving riddles to advance in an investigation.",
        "A file detailing the secret mission of agents working undercover.",
        "Breaking crucial clues during an ongoing investigation.",
        "A lead that is followed in an investigation to solve a case.",
        "A coded message solved to unlock the mystery of a case.",
        "A criminal’s file detailing their involvement in a crime.",
        "A mystery solver working through a case file to solve it.",
        "Tracking a case to uncover secret details about the crime.",
        "Proof documenting findings that support the detective's theory.",
        "A logbook detailing notes made during a detective’s investigation.",
        "Tracking a clue in a case file, leading to a breakthrough.",
        "A detective’s work on a case, progressing through the investigation.",
        "A shadow observing a detective's movements during an investigation.",
        "A report detailing findings crucial to solving a case.",
        "Locked evidence documenting critical information about a mystery.",
        "Cracking a case during an investigation to uncover hidden facts.",
        "Tracking a witness’s role in solving a mystery and recording their information.",
        "A detective’s log documenting progress and breakthroughs in a case.",
        "A sleuth solving a mystery using detailed investigative logs.",
        "Hidden evidence uncovered during an investigation into a crime.",
        "Hunting for clues and evidence that will solve a mystery case.",
        "Breaking a code during an investigation to find key evidence.",
        "A scanner used in a case investigation to detect vital clues.",
        "Bulletproof protection used in a case investigation to ensure safety.",
        "Tracking a pattern in a case that leads to a breakthrough in solving it.",
        "A case that has been closed after a thorough investigation.",
        "Hunting for hidden clues within a detective’s case logs.",
        "An investigation into a mystery case, documented through detailed logs."
    ];

export const words_25 = [ 'MURDERXMYSTERYXFILEXLOGXX', 'CRIMEXSCENEXINVESTIGATION', 'CLUEXHUNTERXTRACKINGXCASE', 'SECRETXAGENTXMISSIONXFILE', 
        'COLDXCASEXFILEXDOCUMENTXX', 'TRAILXLOGXMASTERXREPORTXX', 'WITNESSXREPORTXEVIDENCEXX', 'SLEUTHXFILESXMYSTERYXLOGX', 
        'PISTOLXEVIDENCEXTRACKERXX', 'STAKEOUTXMISSIONXDETECTXX', 'FORENSICXPROBEXCASEXLOGXX', 'SUSPECTXTRACKERXREPORTXXX', 
        'MOTIVEXHUNTERXSECRETXLOGX', 'CRIMEXDEDUCTIONXFILEXLOGX', 'EVIDENCEXLOCKERXMYSTERYXX', 'TRACKINGXAGENTXCASEXFILEX', 
        'CIPHERXMESSAGEXDETECTIVEX', 'DETECTIVEXNOTESXMYSTERYXX', 'WARRANXSEARCHXCASEXLOGXXX', 'PROFILEXMASTERXTRACKINGXX', 
        'CLUESOLVINXMYSTERYXLOGXXX', 'ARCHIVEXREPORTXDETECTIVEX', 'RIDDLEMASTERXTRACKERXXXXX', 'SECRETXMISSIONXFILEXLOGXX', 
        'BREAKINGXCLUEXINVESTIGATE', 'FOLLOWXTHEXLEADXCASEXXXXX', 'CODEDXMESSAGEXMYSTERYXLOG', 'CRIMINALXFILEXTRACKINGXXX', 
        'MYSTERYXSOLVERXCASEXLOGXX', 'CASETRACKINXSECRETXLOGXXX', 'EVIDENCEXPROOFXDETECTIVEX', 'LOGBOOKXMASTERXMYSTERYXXX', 
        'HUNTXTHEXCLUEXFILEXLOGXXX', 'AGENTOPERATESXCASEXLOGXXX', 'SHADOWXTRACKERXMYSTERYXXX', 'REPORTFINDINGXDETECTIVEXX', 
        'LOCKEDXMYSTERYXCASEXLOGXX', 'CRACKINGXCASEXINVESTIGATE', 'WITNESSXSECRETXTRACKINGXX', 'MISSIONXLOGXDETECTIVEXLOG', 
        'TRAILSLEUTHXMYSTERYXLOGXX', 'HIDDENXEVIDENCEXCASEXLOGX', 'PROOFHUNTINGXMYSTERYXXXXX', 'CODEBREAKINGXCASEXLOGXXXX', 
        'SCANNERREPORTXDETECTIVEXX', 'BULLETPROOFXARMORXLOGXXXX', 'HOLDINGPATTERNXCASEXLOGXX', 'CLOSEDXCASEXINVESTIGATION', 
        'CIPHERXHUNTINGXDETECTIVEX', 'INVESTIGATIONXMYSTERYXLOG']

export const words_25_hints = [
                "A file log documenting a murder mystery case.",
                "The investigation of a crime scene.",
                "A person tracking clues to solve a case.",
                "A confidential file detailing a secret agent's mission.",
                "A document related to an unsolved cold case.",
                "A master report logging the trail of evidence.",
                "A witness report containing key evidence.",
                "A log documenting the files related to a mystery solved by a sleuth.",
                "A weapon, used as evidence, being tracked.",
                "A stakeout mission for a detective, typically involving surveillance.",
                "A forensic problem documented in a case log.",
                "A report tracking a suspect's movements and actions.",
                "A log tracking a hunter's motivation behind a secret mission.",
                "A log that deductively analyzes a crime file.",
                "A locker where evidence from a mystery is securely stored.",
                "An agent tracking details in a case file.",
                "A coded message that a detective is trying to decipher.",
                "A detective's notes, crucial for solving a mystery.",
                "A log documenting the search warrant for a case.",
                "The profile of a master tracker following a case.",
                "The process of solving clues to crack a mystery.",
                "A report detailing an archived file of a detective's case.",
                "A master tracker following a riddle's solution.",
                "A secret mission file log maintained by agents.",
                "Breaking a crucial clue in the process of investigation.",
                "Following the lead in a case file for further investigation.",
                "A coded message being solved in the context of a mystery.",
                "A criminal's file being tracked for important evidence.",
                "A mystery solver working on solving a case log.",
                "Tracking the case file to uncover secret clues.",
                "Proof documenting a detective's findings during investigation.",
                "A logbook of important notes from a detective's investigation.",
                "Tracking the clue file during an investigation process.",
                "A detective working through a case log for a mission.",
                "A shadow tracking a detective's mystery-solving process.",
                "A report of findings crucial to a detective's investigation.",
                "A mystery case file being locked for further investigation.",
                "Cracking a case and moving forward with the investigation.",
                "Tracking a witness's actions and secrets during an investigation.",
                "A detective's mission log documenting progress in the case.",
                "A sleuth working through a mystery case log for answers.",
                "Hidden evidence discovered in a case file and logged.",
                "Hunting for concrete evidence to solve a mystery.",
                "Breaking a code related to the case for further investigation.",
                "A scanner report detailing findings from a detective’s case.",
                "Bulletproof armor used during an investigation documented in a case log.",
                "A pattern of case details stored and logged during an investigation.",
                "A closed case after the investigation is completed and documented.",
                "Searching for hidden clues in the detective’s case log.",
                "Investigating a mystery with detailed case logs."
        ]

export const words_36 = [ 'MURDERXMYSTERYXFILEXLOGXDETECTIVEXXX', 'CRIMEXSCENEXINVESTIGATIONXMASTERXLOG', 'CLUEXHUNTERXTRACKINGXCASEXSECRETXXXX', 
        'SECRETXAGENTXMISSIONXFILEXEVIDENCEXX', 'COLDXCASEXFILEXDOCUMENTXTRACKINGXXXX', 'TRAILXLOGXMASTERXREPORTXDETECTIVEXXX', 
        'WITNESSXREPORTXEVIDENCEXHUNTERXCASEX', 'SLEUTHXFILESXMYSTERYXLOGXCIPHERXCASE', 'PISTOLXEVIDENCEXTRACKERXMISSIONXFILE', 
        'STAKEOUTXMISSIONXDETECTIVEXREPORTXXX', 'FORENSICXPROBEXCASEXLOGXSECRETXFILEX', 'SUSPECTXTRACKERXREPORTXMYSTERYXCASEX', 
        'MOTIVEXHUNTERXSECRETXLOGXEVIDENCEXXX', 'CRIMEXDEDUCTIONXFILEXLOGXTRACKINGXXX', 'EVIDENCEXLOCKERXMYSTERYXREPORTXDRXXX', 
        'TRACKINGXAGENTXCASEXFILEXHUNTERXLOGX', 'CIPHERXMESSAGEXDETECTIVEXMYSTERYXXX', 'DETECTIVEXNOTESXMYSTERYXLOGXREPORTXX', 
        'WARRANXSEARCHXCASEXLOGXEVIDENCEXFILE', 'PROFILEXMASTERXTRACKINGXDETECTIVEXXX', 'CLUESOLVINXMYSTERYXLOGXCIPHERXCASEXX', 
        'ARCHIVEXREPORTXDETECTIVEXMISSIONXLOG', 'RIDDLEMASTERXTRACKERXSECRETXFILEXXXX', 'SECRETXMISSIONXFILEXLOGXCLUEXHUNTERX', 
        'BREAKINGXCLUEXINVESTIGATIONXMYSTERYX', 'FOLLOWXTHEXLEADXCASEXDETECTIVEXLOGXX', 'CODEDXMESSAGEXMYSTERYXLOGXREPORTXXXX', 
        'CRIMINALXFILEXTRACKINGXSECRETXCASEXX', 'MYSTERYXSOLVERXCASEXLOGXEVIDENCEXXXX', 'CASETRACKINXSECRETXLOGXDETECTIVEXXXX', 
        'EVIDENCEXPROOFXDETECTIVEXMISSIONXXXX', 'LOGBOOKXMASTERXMYSTERYXREPORTXLOGXXX', 'HUNTXTHEXCLUEXFILEXLOGXTRACKINGXXXXX', 
        'AGENTOPERATESXCASEXLOGXSECRETXXXXXXX', 'SHADOWXTRACKERXMYSTERYXREPORTXXXXXXX', 'REPORTXFINDINGXDETECTIVEXLOGXXXXXXXX', 
        'LOCKEDXMYSTERYXCASEXLOGXHUNTERXXXXXX', 'CRACKINGXCASEXINVESTIGATIONXFILEXXXX', 'WITNESSXSECRETXTRACKINGXMYSTERYXXXXX', 
        'MISSIONXLOGXDETECTIVEXLOGXCASEXXXXXX', 'TRAILSLEUTHXMYSTERYXLOGXREPORTXXXXXX', 'HIDDENXEVIDENCEXCASEXLOGXFILEXXXXXXX', 
        'PROOFHUNTINGXMYSTERYXDETECTXXXXXXXXX', 'CODEXBREAKINGXCASEXLOGXREPORTXXXXXXX', 'SCANNERXREPORTXDETECTIVEXLOGXXXXXXXX', 
        'BULexport constPROOFXMYSTERYXLOGXCASEXXXXXXXX', 'HOLDINGXPATTERNXCASEXLOGXFILEXXXXXXX', 'CLOSEDXCASEXINVESTIGATIONXLOGXXXXXXX', 
        'CIPHERXHUNTINGXDETECTIVEXLOGXXXXXXXX', 'INVESTIGATIONXMYSTERYXLOGXCASEXXXXXX']

export const words_36_hints = [
                "A file log documenting a murder mystery case solved by a detective.",
                "A master log detailing the investigation of a crime scene.",
                "Tracking clues from a case with a secret agent's investigation.",
                "A secret agent mission file, including coded evidence and investigation logs.",
                "A cold case document with detailed tracking information and investigation steps.",
                "A master report logging the trail of evidence discovered during an investigation.",
                "A witness report documenting key evidence for solving a case.",
                "A sleuth’s log, detailing mystery solving and cipher decoding.",
                "A tracker’s log of a weapon used as evidence during an investigation.",
                "A detective’s report on a stakeout mission, collecting surveillance information.",
                "A forensic case log detailing a problem to solve a crime scene investigation.",
                "Tracking and reporting the movements of a suspect during the investigation.",
                "The motivation behind a secret log kept for investigation of a mystery.",
                "A log involving a crime deduction based on tracking and analyzing clues.",
                "A locker containing locked evidence for a case, recorded in a mystery log.",
                "An agent’s log tracking case details during an investigation into a crime.",
                "A detective working through a cipher message in a mystery case.",
                "The notes of a detective, documenting every step of solving a mystery case.",
                "A warrant search log detailing the investigation process in a case.",
                "A profile tracking the movements of a master detective solving a case.",
                "A log documenting the solving of clues and mysteries in case files.",
                "An archive of reports kept by detectives, focusing on solving cases.",
                "A master riddle solver working through clues for mystery case resolution.",
                "A secret mission log file kept by agents working on a case.",
                "Breaking important clues during an investigation process.",
                "Following key leads documented in a case file for further investigation.",
                "Decoding a message related to a mystery, solving the code to gain answers.",
                "Tracking a criminal’s file to uncover evidence related to the case.",
                "A mystery solver working through a case file to find answers.",
                "Tracking the investigation file and uncovering important clues.",
                "Documenting proof found during a detective’s mission and case investigation.",
                "A detective’s logbook containing important investigative notes on a mystery.",
                "Tracking the progress of a clue in the investigation process.",
                "A detective working through case logs to advance their investigation.",
                "A shadow tracking a detective’s investigation progress and findings.",
                "A detailed report documenting a detective’s findings in an investigation.",
                "Locked mystery evidence being logged for future analysis.",
                "Breaking into a case investigation to uncover crucial details.",
                "Tracking a witness’s movements and secrets within a case log.",
                "A detective’s mission log detailing the progress and findings of a case.",
                "A sleuth working through a mystery log to find case resolutions.",
                "Uncovering hidden evidence in a case and documenting findings.",
                "Hunting for clues in a mystery case, searching for critical proof.",
                "Breaking a coded message in a case log to advance the investigation.",
                "Scanning a case for key reports during a detective’s investigation.",
                "Bulletproof armor being logged and documented during an investigation process.",
                "Storing and tracking case patterns that emerge during the investigation.",
                "A case being closed and logged after the investigation concludes.",
                "Hunting for hidden clues within a detective’s log during a mystery.",
                "Documenting the progress and findings of an investigation into a mystery."
            ];


